apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  APP_HOST: {{ .Values.configmap.data.APP_HOST | quote }}
  APP_PORT: {{ .Values.configmap.data.APP_PORT | quote }}
