apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  APP_HOST: {{ .Values.configmap.data.serverHost | quote }}
  APP_PORT: {{ .Values.configmap.data.serverPort | quote }}
