apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.appName }}
spec:
  replicas:  {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app:  {{ .Values.appName }}
  template:
    metadata:
      labels:
        app:  {{ .Values.appName }}
    spec:
      containers:
      - name:  {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.configmap.data.serverPort }}
          name: web
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          limits:
            cpu: "{{ .Values.deployment.resources.limits.cpu }}"
            memory: "{{ .Values.deployment.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.deployment.resources.requests.cpu }}"
            memory: "{{ .Values.deployment.resources.requests.memory }}"
      securityContext:
        runAsUser: {{ .Values.podConfig.securityContext.runAsUser }}
        runAsGroup: {{ .Values.podConfig.securityContext.runAsGroup }}
      strategy:
        type: {{ .Values.deployment.strategy.type }}
        rollingUpdate:
          maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
          maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
