# add namespace when get cluster access
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tengen-tetris
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt/data"
